name: Flake checks

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  check:
    name: Run flake checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Nix
        uses: DeterminateSystems/nix-installer-action@v16
        with:
          extra-conf: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Set up Cachix
        uses: cachix/cachix-action@v16
        with:
          name: tek
          signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
      - name: Free up space
        run: rm -rf /opt/hostedtoolcache
      - name: Run flake checks
        run: nix -L flake check
